#!/bin/bash

echo "***************************"
echo "*  Fixing Permissions *"
echo "***************************"

chmod +x /usr/bin/msfinstaller
echo "[!] msfinstaller Permissions Patched"
echo "[!] Thank you for installing iCTRL"
echo "[!] Follow me on Twitter @noahacks"
echo "[!] Type in Terminal: msfinstaller"
exit 0;
