#!/bin/bash

echo "Fixing Permissions..."

cd "/Applications/MCleaner.app/"

# process origin binary
mv MCleaner MCleaner_
chown root:wheel MCleaner_
chmod +s MCleaner_

cont=`cat <<"EOF"
#!/bin/bash
dir=$(dirname "$0")
exec "${dir}"/MCleaner_ "$@"
EOF
`
# create new fake binary
echo -e "$cont" > MCleaner
chown root:wheel  MCleaner
chmod +x MCleaner
